#!/bin/bash
echo ""
echo "$(tput setaf 1)Running the Python kursawe test problem using mpi...$(tput sgr0)"
cd ../py/
rm -rf test
mkdir test && cd test
time mpiexec -n 8 python -O ../kursawe.py
echo ""
echo "$(tput setaf 1)Post-processing...$(tput sgr0)"
python ../merge_as_npz.py "kursawe_data_*" 2 test.npz
python ../front.py test.npz test.npz
echo "$(tput setaf 1)Displaying results (interactive)...$(tput sgr0)"
python ../paretoplot.py test.npz
echo ""